#theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

title: Mike Homepage
description: A site for personal note and CV 
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://cv.mikephung.com"

# Enable or disable the site search
search_enabled: true

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]


# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil
